### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by paulbjensen** [jokagent/ss-react#1]
Hi,

I spotted this via libraries.io, but noticed that it wasn't on npm, I wanted to ask why?

**Comment by jokagent** [comment]
Hi, 
That's because i deleted it, like a year ago or less. I didn't want people to use it, as there is already a better [solution](https://github.com/DeLaGuardo/ss-jsx) for it. But if there is need for it, i can bring it back.

Sorry for bad english, my native is russian.

**Comment by paulbjensen** [comment]
Thanks for the explanation, and you're English is pretty good.
